export const CREATE_SEQUENCE_REQUEST = "CREATE_SEQUENCE_REQUEST";
export const CREATE_SEQUENCE_SUCCESS = "CREATE_SEQUENCE_SUCCESS";
export const CREATE_SEQUENCE_FAILURE = "CREATE_SEQUENCE_FAILURE";

export const GET_SEQUENCE_REQUEST = "GET_SEQUENCE_REQUEST";
export const GET_SEQUENCE_SUCCESS = "GET_SEQUENCE_SUCCESS";
export const GET_SEQUENCE_FAILURE = "GET_SEQUENCE_FAILURE";

export const DELETE_SEQUENCE_REQUEST = "DELETE_SEQUENCE_REQUEST";
export const DELETE_SEQUENCE_SUCCESS = "DELETE_SEQUENCE_SUCCESS";
export const DELETE_SEQUENCE_FAILURE = "DELETE_SEQUENCE_FAILURE";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAILURE = "GET_COMMENT_FAILURE";

export const UPDATE_COMMENT_REQUEST = "UPDATE_COMMENT_REQUEST";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAILURE = "UPDATE_COMMENT_FAILURE";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";

export const SET_OBJECTS_REQUEST = "SET_OBJECTS_REQUEST";
export const SET_OBJECTS_SUCCESS = "SET_OBJECTS_SUCCESS";
export const SET_OBJECTS_FAILURE = "SET_OBJECTS_FAILURE";